### ISSUE TITLE
Tabs border does not respond to window size change

### ISSUE THREAD

**Issue by kindlychung** [jd-solanki/anu#214]
For example:

![image](https://github.com/jd-solanki/anu/assets/995761/8fbaee6f-6b5c-4ae8-883a-3e647551c067)

**Comment by kindlychung** [comment]
hm, the bug seems to be present only when i added this css rule: 

```css
.a-tabs-wrapper {
    justify-content: center;
}
````
