### ISSUE TITLE
Colors broken with UnoCSS v0.57

### ISSUE THREAD

**Issue by hermit99** [jd-solanki/anu#216]
Looks like with UnoCSS v0.57.0's [breaking changes](https://github.com/unocss/unocss/releases/tag/v0.57.0), Anu's hsla colors are also broken.

Could we align and keep hsla and rgba consistent with tailwindcss too?

**Comment by jd-solanki** [comment]
Hi @hermit99 

Sorry to say but I don't have enough bandwidth to work on this anymore. Feel free to submit a PR I'll surely merge it.

Thanks for raising the issue.

**Comment by hermit99** [comment]
Hi @jd-solanki [PR 218](https://github.com/jd-solanki/anu/pull/218) raised for your review.

**Comment by jingyuexing** [comment]
![image](https://github.com/jd-solanki/anu/assets/19589872/17f1be16-b0d9-422d-8108-61a07558bdba)
the text color:
```css
.text-primary {
    --un-text-opacity: 1;
    color: hsl(var(--a-primary) / var(--un-text-opacity));
}
```
But such css cannot be parsed correctly. The following code is the code that can be parsed correctly.
```css
.text-primary {
    --un-text-opacity: 1;
    color: hsl(var(--a-primary) , var(--un-text-opacity));
}
```
![image](https://github.com/jd-solanki/anu/assets/19589872/0d03df01-371b-4202-b1b2-f1f296b5d8db)
